baseurl = "/"
title = "洗衣机的博客"

theme = "materialize-bp-hugo-theme"

paginate = 10 # Set the number of posts to show before overflowing to the next page.
summaryLength = 100 # Configure how long the post summary should be on the homepage.

enableInlineShortcodes = true
footnoteReturnLinkContents = "^"

defaultContentLanguage = "zh-hans"
#defaultContentLanguageInSubdir = true
hasCJKLanguage = true

copyright = "&copy;{year}, All Rights Reserved"

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
## Change this two to switch between different language
languageCode = "zh-cn"  # For RSS, view https://www.rssboard.org/rss-language-codes

enableRobotsTXT = true
pygmentsCodeFences = true
canonifyurls = true

[author]
name = "Han Chen"

[params]
  description = "Why be a researcher if you can be an Engineer?"
  #images = ["logo.jpg"]
   showPostSummary = true
  # startPageColumns = true
  # showListsGrouped = true
  # alwaysExpandMenu = true
  hideReadingTime = true
  #themeColor1 = "light-green" # main buttons and navbar
  #themeColor1text = "light-green-text"
  #themeColor2 = "red" # footer
  #themeColor2text = "red-text text-lighten-3"

# Sets Social Media icons to appear and link to your account. Value should be your
# username unless otherwise noted.
# Code from https://themes.gohugo.io/future-imperfect/ theme
[social]
  # Coding Communities
  github           = "womeimingzi11"
  # Social Networks
  twitter          = "chenhan1992"
  # Email
  email            = "chenhan28@gmail.com"

[menu]

  [[menu.main]]
    identifier = "about"
    # name = "About"  # Material Icons are displayed as block so use the icon only
    url = "/about/"
    weight = 10
    pre = "<i class='material-icons'>speaker_notes</i>" # Material Icons
    # pre = "<i class='fas fa-heart'></i>" # FontAwesone has more love ;-)

  [[menu.footer]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10
    pre = "<i class='fas fa-address-card'></i>"

  [[menu.footer]]
    identifier = "categories"
    name = "Categories"
    url = "/categories/"
    weight = 20
    pre = "<i class='fas fa-folder'></i>"

  [[menu.footer]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 30
    pre = "<i class='fas fa-tags'></i>"


[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[privacy]

  [privacy.vimeo]
    disable = false
    simple = true

  [privacy.twitter]
    disable = false
    enableDNT = true
    simple = true

  [privacy.instagram]
    disable = false
    simple = true

  [privacy.youtube]
    disable = false
    privacyEnhanced = true

[services]

  [services.instagram]
    disableInlineCSS = true

  [services.twitter]
    disableInlineCSS = true