baseurl = "https://blog.washman.top/"
title = "洗衣机的博客"

theme = "hugo-theme-mixedpaper"

enableRobotsTXT = true
paginate = 10 # Set the number of posts to show before overflowing to the next page.
summaryLength = 100 # Configure how long the post summary should be on the homepage.
pygmentsUseClasses = true # enable theme-defined highlight style

defaultContentLanguage = "zh-hans"
#defaultContentLanguageInSubdir = true
hasCJKLanguage = true

copyright = "&copy;{year}, All Rights Reserved"

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$", "_files$"]
## Change this two to switch between different language
languageCode = "zh-cn"  # For RSS, view https://www.rssboard.org/rss-language-codes

# Add your Google Analytics identifier: UA-XXXXXXXX-X
googleAnalytics = ""

#[taxonomies]
#tag = "tags"

[author]
name = "Han Chen"

[params]
# Blog description at the top of the homepage. Supports markdown.
description = "Why be a researcher if you can be an Engineer?"
showReadMore = false
mainSections = [
	"post",
]
# paginate of archives, tags and categories
listPaginate = 20
postLicense = ""

[params.comment]
type = "none"

# Menu links along the sidebar navigation.
[[menu.main]]
identifier = "about"
name = "About Me"
url = "/about/"
weight = 1 # Weight is an integer used to sort the menu items. The sorting goes from smallest to largest numbers. If weight is not defined for each menu entry, Hugo will sort the entries alphabetically.


[[menu.main]]
identifier = "tags"
name = "Tags"
url = "/tags/"
weight = 2

[[menu.main]]
name = "Posts"
identifier = "posts"
url = "/post/"
weight = 3